#spring.application.name=life-centre-squash

squash.league.host.address=http://localhost:8081/
squash.league.pdf.path=C:\\Users\\hampe\\dbs

# Data
spring.datasource.url=jdbc:h2:file:~/dbs/squash/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=true


Testing
spring.jpa.show-sql=true
hibernate.show_sql=true
spring.h2.console.enabled=true


#spring.application.name=life-centre-squash
#
#logback.configurationFile=/etc/squash/logback.xml
#
#squash.league.host.address=https://plymouthlifecentresquash.co.uk
#squash.league.pdf.path=/var/squash/pdfs
#
#spring.datasource.url=jdbc:h2:file:/opt/squash/db/squashdb;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=true
#spring.h2.console.enabled=false
#
#server.port=8080